name: batchcp
channels:
  - conda-forge
dependencies:
  - anndata
  - awscli
  - rpy2
  - scanpy
  - pandas
  - plotly
  - plottable
  - pip=24.0
  - python=3.11
  - r-matrix
  - r-ggplot2
  - r-mass
  - snakemake-minimal
  - pip:
      - git+https://github.com/johnarevalo/scib.git@frozen_paper
      - pyarrow
      - bbknn
      - git+https://github.com/cytomining/copairs.git@v0.4.1
