name: batchcp
channels:
  - conda-forge
  - bioconda
dependencies:
  - anndata=0.10.6
  - anndata2ri=1.3.1
  - bbknn=1.6.0
  - bioconductor-batchelor=1.14.0
  - cudatoolkit=11.8.0
  - deprecated=1.2.14
  - leidenalg=0.10.2
  - louvain=0.8.2
  - optax=0.2.1
  - pandas=2.2.1
  - pillow=10.3.0
  - pip=24.0
  - plotly=5.19.0
  - plottable=0.1.5
  - pyarrow=12.0.1
  - pydot=2.0.0
  - pymde=0.1.18
  - pynndescent=0.5.12
  - python-igraph=0.10.8
  - pytorch=2.0.0=cuda*
  - r-arrow=12.0.1
  - r-remotes=2.5.0
  - r-seurat=4.4.0
  - r-seuratobject=4.1.4
  - r-matrixstats=1.1.0
  - scanorama=1.7.4
  - scanpy=1.10.0
  - scikit-learn=1.4.1.post1
  - scikit-misc=0.1.4
  - scipy=1.10.0
  - snakemake-minimal=7.32.4
  - snappy=1.1.10
  - tensorflow=2.14.0=cuda*
  - pip:
      - git+https://github.com/johnarevalo/desc.git
      - git+https://github.com/cytomining/copairs.git@v0.4.1
      - git+https://github.com/johnarevalo/scib.git@frozen_paper
