name: batchcp
channels:
  - conda-forge
  - bioconda
dependencies: 
  - anndata
  - awscli
  - rpy2
  - conda>=24.7.1
  - scanpy
  - pandas
  - plotly
  - plottable
  - pip=24.0
  - python=3.11
  - r-matrix
  - r-ggplot2
  - r-mass
  - snakemake
  - pyarrow
  - pip:
      - scib-metrics>=0.5.0
      - bbknn
      - git+https://github.com/cytomining/copairs.git@v0.4.2
